theme: jekyll-theme-leap-day
index_url: 'https://sabinem.github.io/onlinekurstechnik/' 
base_url: 'https://sabinem.github.io/'
description: Hier sammle ich Artikel über Online Kurse, von einem Blog, den ich mal inne hatte.
